image: patrickmckernin/fortunetellerw22

tasks:
  - before: |
      mv /base-rails/gems vendor/bundle
      bundle config set --local path 'vendor/bundle'
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9515
    onOpen: ignore


vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
