image: jelaniwoods/appdev2022-fortune-teller-wip

ports:
  - port: 3000
    onOpen: open-preview
  - port: 9515
    onOpen: ignore


vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
